# This is a config for E2B sandbox template.
# You can use 'template_id' (toyw6mhmdw42n4wyhdcb) or 'template_name (my-slidev-developer) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='my-slidev-developer')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'my-slidev-developer' })

team_id = "df0c5b73-b47c-431e-a90c-9a32db676fb3"
start_cmd = "cd /home/user && npx slidev"
dockerfile = "e2b.Dockerfile"
template_name = "my-slidev-developer"
template_id = "toyw6mhmdw42n4wyhdcb"
